### ISSUE TITLE
asa-server-1 exited with code 3

### ISSUE THREAD

**Issue by bachi76** [mschnitzer/ark-survival-ascended-linux-container-image#104]
When I start the server with `docker compose up -d && docker compose logs -f`, it does its verify thing for a few mins, then shows the two error msgs, that according to other posts are not relevant - but then **exits with code 3** without further info. 

```
...
asa-server-1         | Success! App '2430930' fully installed.
asa-server-1         | Starting the ARK: Survival Ascended dedicated server...
asa-server-1         | Start parameters: TheCenter_WP?listen?Port=7775?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared" 
asa-server-1         | esync: up and running.
asa-server-1         | Failed to read /etc/machine-id, error Invalid argument.
asa-server-1         | wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
asa-server-1 exited with code 3
```

Any ideas?

Thanks - Martin

**Comment by mschnitzer** [comment]
Is this issue still present or can we close this ticket?

**Comment by Jean-LucMakiola** [comment]
Hello, i got the same problem i looked at the log and this was the output: ` Update state (0x5) verifying install, progress: 58.89 (18996120176 / 32256239276)
 Update state (0x5) verifying install, progress: 61.86 (19954450780 / 32256239276)
 Update state (0x5) verifying install, progress: 64.86 (20922492468 / 32256239276)
 Update state (0x5) verifying install, progress: 67.84 (21884003300 / 32256239276)
 Update state (0x5) verifying install, progress: 70.82 (22843186656 / 32256239276)
 Update state (0x5) verifying install, progress: 73.72 (23779509236 / 32256239276)
 Update state (0x5) verifying install, progress: 76.71 (24744347776 / 32256239276)
 Update state (0x5) verifying install, progress: 79.69 (25704800376 / 32256239276)
 Update state (0x5) verifying install, progress: 82.67 (26666917448 / 32256239276)
 Update state (0x5) verifying install, progress: 85.66 (27630428896 / 32256239276)
 Update state (0x5) verifying install, progress: 88.68 (28604974656 / 32256239276)
 Update state (0x5) verifying install, progress: 91.64 (29559562736 / 32256239276)
 Update state (0x5) verifying install, progress: 94.63 (30524043604 / 32256239276)
 Update state (0x5) verifying install, progress: 97.61 (31486052752 / 32256239276)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: Extinction_WP?listen??Port=7777?RCONPort=27020?RCONEnabled=True?ServerAdminPassword=admin -mods=939228,947033 -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared" 
fsync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1738027521
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.00 (0 / 32256239276)
 Update state (0x5) verifying install, progress: 1.61 (519366903 / 32256239276)
 Update state (0x5) verifying install, progress: 4.62 (1489293559 / 32256239276)
 Update state (0x5) verifying install, progress: 7.62 (2459186159 / 32256239276)
 Update state (0x5) verifying install, progress: 10.65 (3436444671 / 32256239276)
 Update state (0x5) verifying install, progress: 13.65 (4402734063 / 32256239276)
 Update state (0x5) verifying install, progress: 16.67 (5376553967 / 32256239276)
 Update state (0x5) verifying install, progress: 19.70 (6354738159 / 32256239276)
 Update state (0x5) verifying install, progress: 22.72 (7329713135 / 32256239276)
 Update state (0x5) verifying install, progress: 25.56 (8243669636 / 32256239276)
 Update state (0x5) verifying install, progress: 28.57 (9215139500 / 32256239276)
 Update state (0x5) verifying install, progress: 31.54 (10172007092 / 32256239276)
 Update state (0x5) verifying install, progress: 34.58 (11152625164 / 32256239276)
 Update state (0x5) verifying install, progress: 37.48 (12088882568 / 32256239276)
 Update state (0x5) verifying install, progress: 40.36 (13019311480 / 32256239276)
 Update state (0x5) verifying install, progress: 43.33 (13976872320 / 32256239276)
 Update state (0x5) verifying install, progress: 46.29 (14931262336 / 32256239276)
 Update state (0x5) verifying install, progress: 49.32 (15909788032 / 32256239276)
 Update state (0x5) verifying install, progress: 52.29 (16865608196 / 32256239276)
 Update state (0x5) verifying install, progress: 55.29 (17833587244 / 32256239276)
 Update state (0x5) verifying install, progress: 58.28 (18800323748 / 32256239276)
 Update state (0x5) verifying install, progress: 61.24 (19753436316 / 32256239276)
 Update state (0x5) verifying install, progress: 64.26 (20729012344 / 32256239276)
 Update state (0x5) verifying install, progress: 67.24 (21689550596 / 32256239276)
 Update state (0x5) verifying install, progress: 70.22 (22650464868 / 32256239276)
 Update state (0x5) verifying install, progress: 73.21 (23615538708 / 32256239276)
 Update state (0x5) verifying install, progress: 76.23 (24590505336 / 32256239276)
 Update state (0x5) verifying install, progress: 79.24 (25558805940 / 32256239276)
 Update state (0x5) verifying install, progress: 82.22 (26519682084 / 32256239276)
 Update state (0x5) verifying install, progress: 85.21 (27486685236 / 32256239276)
 Update state (0x5) verifying install, progress: 88.21 (28453704904 / 32256239276)
 Update state (0x5) verifying install, progress: 91.20 (29416482772 / 32256239276)
 Update state (0x5) verifying install, progress: 94.22 (30391155828 / 32256239276)
 Update state (0x5) verifying install, progress: 97.21 (31357078120 / 32256239276)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: Extinction_WP?listen??Port=7777?RCONPort=27020?RCONEnabled=True?ServerAdminPassword=admin -mods=939228,947033 -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared" 
fsync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1738027521
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...Retrying. . . 
Retrying. . . 
Retrying. . . 
Retrying. . . 
FAILED (No Connection)
Starting the ARK: Survival Ascended dedicated server...
Start parameters: Extinction_WP?listen??Port=7777?RCONPort=27020?RCONEnabled=True?ServerAdminPassword=admin -mods=939228,947033 -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared" 
fsync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Redirecting stderr to '/home/gameserver/Steam/logs/stderr.txt'
Logging directory: '/home/gameserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1738027521
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...Retrying. . . 
Retrying. . . 
Retrying. . . 
`

**Comment by mschnitzer** [comment]
It looks like the container has no network connection, as it cannot connect to Steam (or Steam had an issue at that time). Can you please share your `docker-compose.yml` file? In case you set any passwords, please obfuscate them, before you share that file.

Furthermore, are you using Proxmox?

**Comment by Jean-LucMakiola** [comment]
No Problem: 
```yaml
version: "3.3"
services:
  asa-server-1:
    container_name: asa-server-1
    hostname: asa-server-1
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:latest"
    tty: true
    environment:
      - ASA_START_PARAMS=Extinction_WP?listen??Port=7777?RCONPort=27020?RCONEnabled=True?ServerAdminPassword=*** -mods=939228,947033 -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserv>
      - ENABLE_DEBUG=0
    ports:
      # Game port for player connections through the server browser
      - 0.0.0.0:7777:7777/udp
      # RCON port for remote server administration
      - 0.0.0.0:27020:27020/tcp
    depends_on:
      - set-permissions-1
    volumes:
      - steam-1:/home/gameserver/Steam:rw
      - steamcmd-1:/home/gameserver/steamcmd:rw
      - server-files-1:/home/gameserver/server-files:rw
      - cluster-shared:/home/gameserver/cluster-shared:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      asa-network:
  set-permissions-1:
    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files ; chown -R 25000:25000 /cluster-shared'"
    user: root
    image: "opensuse/leap"
    volumes:
      - steam-1:/steam:rw
      - steamcmd-1:/steamcmd:rw
      - server-files-1:/server-files:rw
      - cluster-shared:/cluster-shared:rw
volumes:
  cluster-shared:
  steam-1:
  steamcmd-1:
  server-files-1:
networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'

 ```
