### ISSUE TITLE
Container doesn't start: wine: RLIMIT_NICE is <= 20, unable to use setpriority safely

### ISSUE THREAD

**Issue by duartejbrito** [mschnitzer/ark-survival-ascended-linux-container-image#19]
I'm getting this error and container doesn't start:

```
...
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27015?RCONEnabled=True -WinLiveMaxPlayers=10 
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

I'm using exactly your docker-compose example. I just changed the RCONPort on start parameters and on exposed ports.

Do you have any idea?

**Comment by mschnitzer** [comment]
```
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

is always shown, but it seems to be more a warning, than an error.

Could you please tell me whether the container exited with exit code 3?
```
docker inspect asa-server-1 | grep Exit
```

Also do you use any form of virtualization? e.g. Proxmox?

**Comment by DarkVentHead** [comment]
> ```
> wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
> ```
> 
> is always shown, but it seems to be more a warning, than an error.
> 
> Could you please tell me whether the container exited with exit code 3?
> 
> ```
> docker inspect asa-server-1 | grep Exit
> ```
> 
> Also do you use any form of virtualization? e.g. Proxmox?

I'll add to this. 

IF VIRTUALIZED - Please make sure to push HOST cpu's through and NOT virtualized cpu's through as they do not have the required instruction set to launch the server.
Verify you have at least 13GB of ram available to the server as i've (personally) found anything less to be slightly unstable.

**Comment by duartejbrito** [comment]
So I'm using a small VPS with 
6 cores | 16 GB and Ubuntu 20.04 (64 Bit) and portainer to manage dockers.
Result of the execution of `docker inspect asa-server-1 | grep Exit` was:
```
"ExistCode":0
```

**Comment by DarkVentHead** [comment]
What is the output of `docker inspect asa-server-1 | grep Status`

**Comment by duartejbrito** [comment]
For `docker inspect asa-server-1 | grep Status` I get: `"Status": "exited"`
And the container is not running.

**Comment by DarkVentHead** [comment]
can you post your docker-compose.yml? Please block all passwords.

**Comment by duartejbrito** [comment]
```
version: "3.3"
services:
  asa-server-1:
    container_name: asa-server-1
    hostname: asa-server-1
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:latest"
    environment:
      - ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27015?RCONEnabled=True -WinLiveMaxPlayers=10
      - ENABLE_DEBUG=0
    ports:
      # Game port for player connections through the server browser
      - 0.0.0.0:7777:7777/udp
      # RCON port for remote server administration
      - 0.0.0.0:27015:27015/tcp
    depends_on:
      - set-permissions-1
    volumes:
      - steam-1:/home/gameserver/Steam:rw
      - steamcmd-1:/home/gameserver/steamcmd:rw
      - server-files-1:/home/gameserver/server-files:rw
    networks:
      asa-network:
  set-permissions-1:
    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files'"
    user: root
    image: "opensuse/leap"
    volumes:
      - steam-1:/steam:rw
      - steamcmd-1:/steamcmd:rw
      - server-files-1:/server-files:rw
#  asa-server-2:
#    container_name: asa-server-2
#    hostname: asa-server-2
#    entrypoint: "/usr/bin/start_server"
#    user: gameserver
#    image: "mschnitzer/asa-linux-server:latest"
#    environment:
#      - ASA_START_PARAMS=TheIsland_WP?listen?Port=7778?RCONPort=27021?RCONEnabled=True -WinLiveMaxPlayers=50
#    ports:
#      # Game port for player connections through the server browser
#      - 0.0.0.0:7778:7778/udp
#      # RCON port for remote server administration
#      - 0.0.0.0:27021:27021/tcp
#    depends_on:
#      - set-permissions-2
#    volumes:
#      - steam-2:/home/gameserver/Steam:rw
#      - steamcmd-2:/home/gameserver/steamcmd:rw
#      - server-files-2:/home/gameserver/server-files:rw
#    networks:
#      asa-network:
#  set-permissions-2:
#    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files'"
#    user: root
#    image: "opensuse/leap"
#    volumes:
#      - steam-2:/steam:rw
#      - steamcmd-2:/steamcmd:rw
#      - server-files-2:/server-files:rw
volumes:
  steam-1:
  steamcmd-1:
  server-files-1:
#  steam-2:
#  steamcmd-2:
#  server-files-2:
networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'
```
