### ISSUE TITLE
Failed to read /etc/machine-id, error invalid argument

### ISSUE THREAD

**Issue by DarkVentHead** [mschnitzer/ark-survival-ascended-linux-container-image#6]
Currently receiving this. States Ark server is starting then gets:

Failed to read /etc/machine-id, error invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriotity safely

Then containers crash. 

Any suggestions?

**Comment by mschnitzer** [comment]
Does it really crash? /etc/machine-id holds unique identifier of your system. However it is not present in a docker container. I noticed this error when preparing the image but I eventually ignored it since it haven't had any impact on the ASA server.

In which way does the container crash? As I'm receiving these issues as well, but the container continues running and spins up the ASA server just fine.

Don't get confused, this is actually the last message you are seeing in the log and this is expected. For my server it looks like this in the console:

```
[...]
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.03 (2383743 / 9527225554)
 Update state (0x5) verifying install, progress: 3.37 (321542919 / 9527225554)
 Update state (0x5) verifying install, progress: 9.56 (910395647 / 9527225554)
 Update state (0x5) verifying install, progress: 15.63 (1489216639 / 9527225554)
 Update state (0x5) verifying install, progress: 21.67 (2064884863 / 9527225554)
 Update state (0x5) verifying install, progress: 27.76 (2644315115 / 9527225554)
 Update state (0x5) verifying install, progress: 33.87 (3227331539 / 9527225554)
 Update state (0x5) verifying install, progress: 39.99 (3809655111 / 9527225554)
 Update state (0x5) verifying install, progress: 46.03 (4385323335 / 9527225554)
 Update state (0x5) verifying install, progress: 52.04 (4957845831 / 9527225554)
 Update state (0x5) verifying install, progress: 58.08 (5533526622 / 9527225554)
 Update state (0x5) verifying install, progress: 64.35 (6130495218 / 9527225554)
 Update state (0x5) verifying install, progress: 70.62 (6728183538 / 9527225554)
 Update state (0x5) verifying install, progress: 76.89 (7325871858 / 9527225554)
 Update state (0x5) verifying install, progress: 83.06 (7913316901 / 9527225554)
 Update state (0x5) verifying install, progress: 89.19 (8497363493 / 9527225554)
 Update state (0x5) verifying install, progress: 95.42 (9090572853 / 9527225554)
Success! App '2430930' fully installed.
Starting the ARK: Survival Ascended dedicated server now...
esync: up and running.
Failed to read /etc/machine-id, error Invalid argument.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
```

Just run the container again and check with `docker ps` whether the container is still running once the logs reach that line complaining about `/etc/machine-id`. `docker ps` should tell you whether the container is still running or not.

**Comment by DarkVentHead** [comment]
It does in fact crash:
![image](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/82452886/2d45d0b6-f3ab-46b5-adeb-027bd105b66a)

Interesting change in log output. Maybe a sign? Yours states: esync: up and running. Mine states: fsync: up and running.

**Comment by mschnitzer** [comment]
Interesting, seems to be Proton related. For some people it seems to crash, for others it doesn't.
https://github.com/ValveSoftware/Proton/issues/6141

What specs does your server have and what OS are you using?

**Comment by mschnitzer** [comment]
And please also attach the output section "State" of `docker inspect asa-server`.

**Comment by EvilSeeQ** [comment]
Encountering the exact same issue where it just exits with Exit code 0.

The docker inspect results in:
```
"State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-11-03T16:07:53.044269448Z",
            "FinishedAt": "2023-11-03T16:08:53.315133763Z"
        },
```
and when running `docker events`  i get the following when the asa-server container dies:

```
2023-11-03T17:13:24.513633109+01:00 network disconnect d58f40dd1fb5071975fb26d73df02bb35ebebd5e593be230d30458918554c6a8 (container=f75d1a5ca75bf30fa1011f9384858e8c0c79c8861e7425c4fd1c679d3fb0dbaa, name=ark_default, type=bridge)
2023-11-03T17:13:24.543690886+01:00 volume unmount ark_steam (container=f75d1a5ca75bf30fa1011f9384858e8c0c79c8861e7425c4fd1c679d3fb0dbaa, driver=local)
2023-11-03T17:13:24.543729555+01:00 volume unmount ark_server-files (container=f75d1a5ca75bf30fa1011f9384858e8c0c79c8861e7425c4fd1c679d3fb0dbaa, driver=local)
2023-11-03T17:13:24.543740315+01:00 volume unmount ark_steamcmd (container=f75d1a5ca75bf30fa1011f9384858e8c0c79c8861e7425c4fd1c679d3fb0dbaa, driver=local)
2023-11-03T17:13:24.569961970+01:00 container die f75d1a5ca75bf30fa1011f9384858e8c0c79c8861e7425c4fd1c679d3fb0dbaa (com.docker.compose.config-hash=9300acb67affb64f0b6807508bff68b337b30bbc3d1b0fd9af9b5148b52eba21, com.docker.compose.container-number=1, com.docker.compose.depends_on=set-permissions:service_started:false, com.docker.compose.image=sha256:0cff9388e6fe9aee6e6383a092281fea70925af462aac3da3192696368c519cb, com.docker.compose.oneoff=False, com.docker.compose.project=ark, com.docker.compose.project.config_files=/home/username/ARK/docker-compose.yml, com.docker.compose.project.working_dir=/home/username/ARK, com.docker.compose.service=server, com.docker.compose.version=2.21.0, execDuration=63, exitCode=0, image=mschnitzer/asa-linux-server, name=asa-server)
```

**Comment by EvilSeeQ** [comment]
WSL2 defaults to 8GB, increased to 16GB now and the container seem to be running just fine now without exiting the last 10 minutes.

**Comment by DarkVentHead** [comment]
Interesting. I'll be increasing memory as well and will report back!

**Comment by DarkVentHead** [comment]
> Interesting, seems to be Proton related. For some people it seems to crash, for others it doesn't. [ValveSoftware/Proton#6141](https://github.com/ValveSoftware/Proton/issues/6141)
> 
> What specs does your server have and what OS are you using?

It's a VM (proxmox host) of debian 12 (non-gui) with 6 cpu's and 20GB (upped from 12GB initially) ram. Attached is out of docker inspect:
 
![image](https://github.com/mschnitzer/ark-survival-ascended-linux-container-image/assets/82452886/03ca773e-2c1f-435f-a5e9-64945aa380aa)

**Comment by DarkVentHead** [comment]
I suspect there's a distinct difference between esync and fsync and someone also mentioned in the proton issue discussion.

**Comment by DarkVentHead** [comment]
I was unable to test this theory. Would you be willing to add a tag for testing that disables FSYNC in Proton?

PROTON_NO_FSYNC=1

**Comment by mschnitzer** [comment]
You mean a docker image tag that sets a bash environment variable `PROTON_NO_FSYNC=1` ?

**Comment by DarkVentHead** [comment]
Yes Sir. Just to force esync to take over.

**Comment by mschnitzer** [comment]
You can actually set it yourself by editing the `docker-compose.yml` file.

```yml
version: "3.3"
services:
  server:
    container_name: asa-server
    hostname: asa-server
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server"
    stdin_open: true
    tty: true
    environment:
      - PROTON_NO_FSYNC=1
    ports:
      - 0.0.0.0:7777:7777/udp
      - 0.0.0.0:27020:27020/tcp
    depends_on:
      - set-permissions
    volumes:
      - steam:/home/gameserver/Steam:rw
      - steamcmd:/home/gameserver/steamcmd:rw
      - server-files:/home/gameserver/server-files:rw
    networks:
      default:
  set-permissions:
    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files'"
    user: root
    image: "opensuse/leap"
    volumes:
      - steam:/steam:rw
      - steamcmd:/steamcmd:rw
      - server-files:/server-files:rw
volumes:
  steam:
  steamcmd:
  server-files:
networks:
  default:
    attachable: true
```

Could you please report whether that fixes your issue?
