### ISSUE TITLE
Custom volume paths

### ISSUE THREAD

**Issue by Kivarnis** [mschnitzer/ark-survival-ascended-linux-container-image#64]
Unless I am simply inept (Possible, only just learning docker) there is no way to set your own volume paths so that data goes where you want it to go. I need to be able to specify where all the data is stored.

**Comment by mschnitzer** [comment]
It is possible to define your own paths, but let me ask you why you want a different path? Multiple disks/NFS mounts?

**Comment by Kivarnis** [comment]
Awesome thank you. And yes i have something like 15 disks in this server plus it does a fair few differing tasks for me which requires a bit of organization to keep track of what is where for my own sanity.

**Comment by mschnitzer** [comment]
Alright, can we close this issue then? Have your questions been answered?

**Comment by Kivarnis** [comment]
> Yes, but for the sake of OCD, can I move all the volumes this way? My attempt to do so ran into permission issues in a hurry. It's ultimately fine if not but I am slightly OCD when it comes to organizing everything.

Actually no, trying this resulted in the following.


Success! App '2430930' fully installed.
mkdir: cannot create directory '/home/gameserver/server-files/steamapps': Permission denied
cp: cannot create directory '/home/gameserver/server-files/steamapps/compatdata/2430930': No such file or directory
Starting the ARK: Survival Ascended dedicated server...
Start parameters: TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared" 
/usr/bin/start_server: line 49: cd: /home/gameserver/server-files/ShooterGame/Binaries/Win64: No such file or directory
Traceback (most recent call last):
  File "/home/gameserver/Steam/compatibilitytools.d/GE-Proton8-21/proton", line 1903, in <module>
    g_session.init_session(sys.argv[1] != "runinprefix")
  File "/home/gameserver/Steam/compatibilitytools.d/GE-Proton8-21/proton", line 1683, in init_session
    g_compatdata.setup_prefix()
  File "/home/gameserver/Steam/compatibilitytools.d/GE-Proton8-21/proton", line 776, in setup_prefix
    with self.prefix_lock:
  File "/home/gameserver/Steam/compatibilitytools.d/GE-Proton8-21/filelock.py", line 323, in __enter__
    self.acquire()
  File "/home/gameserver/Steam/compatibilitytools.d/GE-Proton8-21/filelock.py", line 271, in acquire
    self._acquire()
  File "/home/gameserver/Steam/compatibilitytools.d/GE-Proton8-21/filelock.py", line 384, in _acquire
    fd = os.open(self._lock_file, open_mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/gameserver/server-files/steamapps/compatdata/2430930/pfx.lock'

**Comment by Kivarnis** [comment]
Same error, no change, server fails to start.

**Comment by mschnitzer** [comment]
What's the path you want the server to be installed at? I'll make an example of a `docker-compose.yml` file then.

**Comment by mschnitzer** [comment]
So please use this `docker-compose.yml` instead:

```yml
version: "3.3"
services:
  asa-server-1:
    container_name: asa-server-1
    hostname: asa-server-1
    entrypoint: "/usr/bin/start_server"
    user: gameserver
    image: "mschnitzer/asa-linux-server:latest"
    environment:
      - ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared"
      - ENABLE_DEBUG=0
    ports:
      # Game port for player connections through the server browser
      - 0.0.0.0:7777:7777/udp
      # RCON port for remote server administration
      - 0.0.0.0:27020:27020/tcp
    depends_on:
      - set-permissions-1
    volumes:
      - /home/kiva/ArkAscended/steam-1:/home/gameserver/Steam:rw
      - /home/kiva/ArkAscended/steamcmd-1:/home/gameserver/steamcmd:rw
      - /home/kiva/ArkAscended/server-files-1:/home/gameserver/server-files:rw
      - /home/kiva/ArkAscended/cluster-shared:/home/gameserver/cluster-shared:rw
      - /etc/localtime:/etc/localtime:ro
    networks:
      asa-network:
  set-permissions-1:
    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files ; chown -R 25000:25000 /cluster-shared'"
    user: root
    image: "opensuse/leap"
    volumes:
      - /home/kiva/ArkAscended/steam-1:/steam:rw
      - /home/kiva/ArkAscended/steamcmd-1:/steamcmd:rw
      - /home/kiva/ArkAscended/server-files-1:/server-files:rw
      - /home/kiva/ArkAscended/cluster-shared:/cluster-shared:rw
#  asa-server-2:
#    container_name: asa-server-2
#    hostname: asa-server-2
#    entrypoint: "/usr/bin/start_server"
#    user: gameserver
#    image: "mschnitzer/asa-linux-server:latest"
#    environment:
#      - ASA_START_PARAMS=ScorchedEarth_WP?listen?Port=7778?RCONPort=27021?RCONEnabled=True -WinLiveMaxPlayers=50 -clusterid=default -ClusterDirOverride="/home/gameserver/cluster-shared"
#    ports:
#      # Game port for player connections through the server browser
#      - 0.0.0.0:7778:7778/udp
#      # RCON port for remote server administration
#      - 0.0.0.0:27021:27021/tcp
#    depends_on:
#      - set-permissions-2
#    volumes:
#      - steam-2:/home/gameserver/Steam:rw
#      - steamcmd-2:/home/gameserver/steamcmd:rw
#      - server-files-2:/home/gameserver/server-files:rw
#      - cluster-shared:/home/gameserver/cluster-shared:rw
#      - /etc/localtime:/etc/localtime:ro
#    networks:
#      asa-network:
#  set-permissions-2:
#    entrypoint: "/bin/bash -c 'chown -R 25000:25000 /steam ; chown -R 25000:25000 /steamcmd ; chown -R 25000:25000 /server-files ; chown -R 25000:25000 /cluster-shared'"
#    user: root
#    image: "opensuse/leap"
#    volumes:
#      - steam-2:/steam:rw
#      - steamcmd-2:/steamcmd:rw
#      - server-files-2:/server-files:rw
#      - cluster-shared:/cluster-shared:rw
#  steam-2:
#  steamcmd-2:
#  server-files-2:
networks:
  asa-network:
    attachable: true
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: 'asanet'
```

Please run the following commands before you execute any docker or docker-compose commands:

```
mkdir -p /home/kiva/ArkAscended/steam-1
mkdir -p /home/kiva/ArkAscended/steamcmd-1
mkdir -p /home/kiva/ArkAscended/server-files-1
mkdir -p /home/kiva/ArkAscended/cluster-shared
```

This creates the directories used by docker.

Now delete the existing container:

```
docker stop-asa-server-1
docker rm -f asa-server-1
```

This stops and deletes any existing container.

Now run `docker-compose up -d` and it should make use of your volumes.
