### ISSUE TITLE
Volume location change?

### ISSUE THREAD

**Issue by JKAF3** [mschnitzer/ark-survival-ascended-linux-container-image#91]
Hi, I’m new to Linux and docker so I’m still learning however, following your guide I make a directory and copy the compose file over then start the container and according to you (step 5 of guide) “The location of these volumes is /var/lib/docker/volumes”
My question is, if I want ALL of the files related to the ASA container to be in “/var/docker/ark/ark_aberation/“ which is where I will copy the yml file to, how would I change it so the volumes it installs will be in there instead of “The location of these volumes is /var/lib/docker/volumes”?

Again, I’m new so apologies for the dumb question (if it is one)

**Comment by mschnitzer** [comment]
I didn't test it, but in theory it should work like this:

```yml
volumes:
  cluster-shared:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker/ark/cluster-shared
  steam-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker/ark/ark_aberation/steam-1
  steamcmd-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker/ark/ark_aberation/steamcmd-1
  server-files-1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/docker/ark/ark_aberation/server-files-1
```
