### ISSUE TITLE
Common Server Files/Seperate Config Files

### ISSUE THREAD

**Issue by DalinSprocket** [mschnitzer/ark-survival-ascended-linux-container-image#99]
First off, I love this, and have had no issues with it working. With ASA you are able to run multiple instances of the game off the same binary. I'm no docker expert but with some tweaking and a little manual intervention I was able to run 5 servers off of 1 install. I was just wondering why that was not done by default? There may be a technical reason that I'm missing but I installed the server to server-files with the configs (GameUserSettings.ini and Game.ini) under TheIslandConfig, TheCenterConfig, AberrationConfig, etc... This allowed me to use only the 30GB + Save data for all 5 maps rather then the default 150GB.

**Comment by Mok-sea** [comment]
> First off, I love this, and have had no issues with it working. With ASA you are able to run multiple instances of the game off the same binary. I'm no docker expert but with some tweaking and a little manual intervention I was able to run 5 servers off of 1 install. I was just wondering why that was not done by default? There may be a technical reason that I'm missing but I installed the server to server-files with the configs (GameUserSettings.ini and Game.ini) under TheIslandConfig, TheCenterConfig, AberrationConfig, etc... This allowed me to use only the 30GB + Save data for all 5 maps rather then the default 150GB.

Would you mind explaning this in more detail?

**Comment by DalinSprocket** [comment]
> Would you mind explaining this in more detail?
I will do my best, as this is the first time I've really messed with docker/docker-compose so my terminology my be incorrect.
For each container in the docker-compose.yml under the volumes I modified the lines
- server-files-1:/home/gameserver/server-files:rw
to
- server-files:/home/gameserver/server-files:rw (just removed the -1, -2, -3, etc...)
this causes all the containers to use the same shared folder for the binary to run the game, thus only needing to download it once

Then add the mount points to expose the configs (GameUserSettings.ini and Game.ini) for the respective containers

TheIslandConfig:/home/gameserver/server-files/ShooterGame/Saved/Config/WindowsServer:rw
TheCenterConfig:/home/gameserver/server-files/ShooterGame/Saved/Config/WindowsServer:rw
etc.

I tried to modify the set-permissions-(1,2,3,4,5) to auto set the permissions but I screwed that up somehow and manually had to change it after the fact so I can only tell you what I did to fix it.
I had to manually 
`chown -R 25000:25000 server-files/ShooterGame/Saved/Config/WindowsServer`
if the directory does not exist you may have to create it first.
`chown -R 25000:25000 TheIslandConfig` (do this for each server you are installing)
after running `docker-compose up -d` I stopped them all before downloading the game since they are sharing the same mount point and they will trip over each other during the install.

start a single container with `docker start asa-server-1` 
wait for it to complete the download and start.
Once it's done you can stop it `docker stop asa-server-1` and edit the server settings like the server name in TheIslandConfig/GameUserSettings.ini (or whatever map you started)
restart the server `docker start asa-server-1`

After you make sure it's up and running you can then start all the other servers
`docker start asa-server-2`
`docker start asa-server-3`...

The new servers will not have to download the base game and just have to verify the files via steamcmd.
Once those have started you can then edit their respective (map)Config/ files to change server name, passwords, etc.

Hopefully I did not make that too confusing, as I was just learning the stuff as I went along myself.

**Comment by mschnitzer** [comment]
There was no specific reason why I choose not going down that route so far. I just didn't look into how this works. I'm fairly confident that it can be integrated in the container or in the README. I'd just need to dedicate some time to test this. I'm keeping this for the future, thanks for the suggestion.

**Comment by axieum** [comment]
Here's my `docker-compose.yaml` file -

```yaml
services:
  # ARK: The Island
  ark-the-island:
    image: docker.io/mschnitzer/asa-linux-server:latest
    container_name: ark-the-island
    entrypoint: /usr/bin/start_server
    restart: unless-stopped
    user: gameserver
    tty: true
    networks:
      - ark
    ports:
      - 7777:7777/udp  # Game
      - 27020:27020/tcp  # RCON
    environment:
      - ASA_START_PARAMS=TheIsland_WP?listen?Port=7777?RCONPort=27020?RCONEnabled=True -NoBattlEye -converttostore -usestore -BackupTransferPlayerDatas -WinLiveMaxPlayers=16 -clusterid="[REDACTED]" -ClusterDirOverride="/home/gameserver/cluster-shared" -mods=928603,929420,929785,929811,929838,930025,930389,935408,935985,936407,942024,942989,949310,951574,953154,968201,987881
      - ENABLE_DEBUG=0
    volumes:
      - ark-server:/home/gameserver/server-files:rw
      - ark-steam:/home/gameserver/Steam:rw
      - ark-steamcmd:/home/gameserver/steamcmd:rw
      - ./cluster:/home/gameserver/cluster-shared:rw
      - ./ark-the-island:/home/gameserver/server-files/ShooterGame/Saved:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - set-permissions

  # ARK: Scorched Earth
  ark-scorched-earth:
    image: docker.io/mschnitzer/asa-linux-server:latest
    container_name: ark-scorched-earth
    entrypoint: /usr/bin/start_server
    restart: unless-stopped
    user: gameserver
    tty: true
    networks:
      - ark
    ports:
      - 7778:7778/udp  # Game
      - 27021:27021/tcp  # RCON
    environment:
      - ASA_START_PARAMS=ScorchedEarth_WP?listen?Port=7778?RCONPort=27021?RCONEnabled=True -NoBattlEye -converttostore -usestore -BackupTransferPlayerDatas -WinLiveMaxPlayers=16 -clusterid="[REDACTED]" -ClusterDirOverride="/home/gameserver/cluster-shared" -mods=928603,929420,929785,929811,929838,930025,930389,935408,935985,936407,942024,942989,949310,951574,953154,968201,987881
      - ENABLE_DEBUG=0
    volumes:
      - ark-server:/home/gameserver/server-files:rw
      - ark-steam:/home/gameserver/Steam:rw
      - ark-steamcmd:/home/gameserver/steamcmd:rw
      - ./cluster:/home/gameserver/cluster-shared:rw
      - ./ark-scorched-earth:/home/gameserver/server-files/ShooterGame/Saved:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - set-permissions

  # ARK: The Center
  ark-the-center:
    image: docker.io/mschnitzer/asa-linux-server:latest
    container_name: ark-the-center
    entrypoint: /usr/bin/start_server
    restart: unless-stopped
    user: gameserver
    tty: true
    networks:
      - ark
    ports:
      - 7779:7779/udp  # Game
      - 27022:27022/tcp  # RCON
    environment:
      - ASA_START_PARAMS=TheCenter_WP?listen?Port=7779?RCONPort=27022?RCONEnabled=True -NoBattlEye -converttostore -usestore -BackupTransferPlayerDatas -WinLiveMaxPlayers=16 -clusterid="[REDACTED]" -ClusterDirOverride="/home/gameserver/cluster-shared" -mods=928603,929420,929785,929811,929838,930025,930389,935408,935985,936407,942024,942989,949310,951574,953154,968201,987881
      - ENABLE_DEBUG=0
    volumes:
      - ark-server:/home/gameserver/server-files:rw
      - ark-steam:/home/gameserver/Steam:rw
      - ark-steamcmd:/home/gameserver/steamcmd:rw
      - ./cluster:/home/gameserver/cluster-shared:rw
      - ./ark-the-center:/home/gameserver/server-files/ShooterGame/Saved:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - set-permissions

  # ARK: Aberration
  ark-aberration:
    image: docker.io/mschnitzer/asa-linux-server:latest
    container_name: ark-aberration
    entrypoint: /usr/bin/start_server
    restart: unless-stopped
    user: gameserver
    tty: true
    networks:
      - ark
    ports:
      - 7780:7780/udp  # Game
      - 27023:27023/tcp  # RCON
    environment:
      - ASA_START_PARAMS=Aberration_WP?listen?Port=7780?RCONPort=27023?RCONEnabled=True -NoBattlEye -converttostore -usestore -BackupTransferPlayerDatas -WinLiveMaxPlayers=16 -clusterid="[REDACTED]" -ClusterDirOverride="/home/gameserver/cluster-shared" -mods=928603,929420,929785,929811,929838,930025,930389,935408,935985,936407,942024,942989,949310,951574,953154,968201,987881
      - ENABLE_DEBUG=0
    volumes:
      - ark-server:/home/gameserver/server-files:rw
      - ark-steam:/home/gameserver/Steam:rw
      - ark-steamcmd:/home/gameserver/steamcmd:rw
      - ./cluster:/home/gameserver/cluster-shared:rw
      - ./ark-aberration:/home/gameserver/server-files/ShooterGame/Saved:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - set-permissions

  # ARK: Extinction
  ark-extinction:
    image: docker.io/mschnitzer/asa-linux-server:latest
    container_name: ark-extinction
    entrypoint: /usr/bin/start_server
    restart: unless-stopped
    user: gameserver
    tty: true
    networks:
      - ark
    ports:
      - 7781:7781/udp  # Game
      - 27024:27024/tcp  # RCON
    environment:
      - ASA_START_PARAMS=Extinction_WP?listen?Port=7781?RCONPort=27024?RCONEnabled=True -NoBattlEye -WinLiveMaxPlayers=16 -usestore -BackupTransferPlayerDatas -clusterid="[REDACTED]" -ClusterDirOverride="/home/gameserver/cluster-shared" -mods=928603,929420,929785,929811,929838,930025,930389,935408,935985,936407,942024,942989,949310,951574,953154,968201,987881
      - ENABLE_DEBUG=0
    volumes:
      - ark-server:/home/gameserver/server-files:rw
      - ark-steam:/home/gameserver/Steam:rw
      - ark-steamcmd:/home/gameserver/steamcmd:rw
      - ./cluster:/home/gameserver/cluster-shared:rw
      - ./ark-extinction:/home/gameserver/server-files/ShooterGame/Saved:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - set-permissions

  # Permissions Helper
  set-permissions:
    image: docker.io/opensuse/leap
    container_name: set-permissions
    # NB: 1001 is the host system's UID for the "ark" user
    entrypoint: >-
      /bin/bash -c '
      chown -R 25000:25000 /steam;
      chown -R 25000:25000 /steamcmd;
      chown -R 25000:1001  /server-files;
      chown -R 25000:1001  /cluster-shared'
    user: root
    volumes:
      - ark-server:/server-files:rw
      - ark-steam:/steam:rw
      - ark-steamcmd:/steamcmd:rw
      - ./cluster:/cluster-shared:rw
      - ./ark-the-island:/server-files/the-island:rw
      - ./ark-scorched-earth:/server-files/scorched-earth:rw
      - ./ark-the-center:/server-files/the-center:rw
      - ./ark-aberration:/server-files/aberration:rw
      - ./ark-extinction:/server-files/extinction:rw

volumes:
  ark-server:
  ark-steam:
  ark-steamcmd:

networks:
  ark:
    attachable: true
```

Here's my directory structure -

```
.
└── ark-aberration
    └── Config
        └── WindowsServer
    └── Logs
    └── SaveGames
    └── SavedArks
        └── Aberration_WP

└── ark-extinction
    └── Config
        └── WindowsServer
    └── Logs
    └── SaveGames
    └── SavedArks
        └── Extinction_WP

└── ark-scorched-earth
    └── Config
    │   └── WindowsServer
    └── Logs
    └── SaveGames
    └── SavedArks
        └── ScorchedEarth_WP

└── ark-the-center
    └── Config
        └── WindowsServer
    └── Logs
    └── SaveGames
    └── SavedArks
        └── TheCenter_WP

└── ark-the-island
    └── Config
        └── WindowsServer
    └── Logs
    └── SaveGames
    └── SavedArks
        └── TheIsland_WP

└── cluster
    └── clusters
        └── ...
```

Since my server only has 32GiB RAM, I can only run two ARKs at a time.

```
docker compose up -d ark-the-island ark-extinction
```

Since the installation files are now shared, if there has been a game update, we must bring down all containers and boot up one that will update the installation files before we boot up other ARKs.

```
docker exec -t ark-the-island asa-ctrl rcon --exec 'saveworld'
docker exec -t ark-extinction asa-ctrl rcon --exec 'saveworld'
docker compose down
docker compose up -d ark-the-island
docker compose logs -f
# once updated, CTRL-C, and boot up the remaining ARKs
docker compose up -d ark-extinction
```
